In [42]:
# Pakages needed
import os
import cv2
import keras
from keras.applications import InceptionV3
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.models import Model
import numpy as np
import random
from keras.models import load_model
from keras.utils import to_categorical
from sklearn.utils import shuffle
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM

In [ ]:
# Load the pretrained InceptionV3 model and restructure it to get feature vector from last pool layer
model = InceptionV3()
# re-structure the model
model.layers.pop()
model = Model(inputs=model.inputs, outputs=model.layers[-1].output)

In [3]:
# extract features from each frame in video in the directory
def extract_features(vid):
    # extract features from each photo
    features = []
    labels = []
    for name in os.listdir(vid):
        # Label
        label = (os.path.join(vid,name)).split('/')[-1]
        label = label.split('_')[0]
       
        # Capture frames from Video
        vidcap = cv2.VideoCapture(os.path.join(vid,name))
        success,image = vidcap.read()
        
        while success:
            success,image = vidcap.read()
            cv2.imwrite(os.path.join(os.getcwd(),'saved.jpg'), image)
            try:
                image = load_img(os.path.join(os.getcwd(),'saved.jpg'), target_size=(299, 299))
                # convert the image pixels to a numpy array
                image = img_to_array(image)
                # reshape data for the model
                image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
                # prepare the image for the inception model
                image = keras.applications.inception_v3.preprocess_input(image)
                # get features
                feature = model.predict(image, verbose=0)
            
                features.append([feature])
                labels.append(int(label))
                print("In progress")
            except:
                pass
    return features,labels

In [4]:
# extract features from all images
directory = '/home/ketakiw/deep-learning/videos/train'
features,labels = extract_features(directory)
print('Extracted Features: %d' % len(features))

In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In p

In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In p

In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In p

In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In p

In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In progress
In p

In [5]:
total_frames = len(features)
print(labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [6]:
# Convert labels into one-hot vector
labels2 = to_categorical(labels)
print(labels2)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [32]:
main_features = features
main_labels = labels2

In [33]:
# Shuffle features and labels together
list_1 = main_features
list_2 = main_labels
list_1, list_2 = shuffle(list_1, list_2)
print(list_2)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [34]:
# List to numpy array
transfer_values = np.array(features)
labels_train = np.array(labels2)

In [35]:
# Reshape numpy array
transfer_values = np.reshape(transfer_values,(total_frames,2048))

In [36]:
len(transfer_values)

2926

In [14]:
# Creating chunks of 15 features and respective labels
frames_num=15
count = 0
joint_transfer=[]

for i in range(int(len(transfer_values)/frames_num)):

    inc = count+frames_num

    joint_transfer.append([transfer_values[count:inc],labels_train[count]])

    count =inc

In [15]:
# RNN architecture
chunk_size = 2048
n_chunks = 15
rnn_size = 512

model = Sequential()

model.add(LSTM(rnn_size, input_shape=(n_chunks, chunk_size)))

model.add(Dense(1024))

model.add(Activation('relu'))

model.add(Dense(50))

model.add(Activation('sigmoid'))

model.add(Dense(4))

model.add(Activation('softmax'))

model.compile(loss='mean_squared_error', optimizer='adam',metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 512)               5244928   
_________________________________________________________________
dense_1 (Dense)              (None, 1024)              525312    
_________________________________________________________________
activation_95 (Activation)   (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                51250     
_________________________________________________________________
activation_96 (Activation)   (None, 50)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 204       
_________________________________________________________________
activation_97 (Activation)   (None, 4)                 0         
Total para

In [17]:
# Training loop
data =[]
target=[]
epoch = 5
batchS = 4

for i in joint_transfer:
    data.append(i[0])
    target.append(np.array(i[1]))

model.fit(np.array(data), np.array(target), epochs=epoch, batch_size=batchS, verbose=1)

Epoch 1/5
195/195 [==============================] - 30s 152ms/step - loss: 0.1886 - acc: 0.3026
Epoch 2/5
195/195 [==============================] - 28s 143ms/step - loss: 0.1812 - acc: 0.3795
Epoch 3/5
195/195 [==============================] - 28s 142ms/step - loss: 0.1878 - acc: 0.3282
Epoch 4/5
195/195 [==============================] - 28s 142ms/step - loss: 0.1831 - acc: 0.3231
Epoch 5/5
195/195 [==============================] - 28s 146ms/step - loss: 0.1861 - acc: 0.3641


In [18]:
# Model Save
model.save("rnn.h5", overwrite=True)

### Testing on single video

In [26]:
# Load model
test_model = load_model("rnn.h5")

In [29]:
# Create chunks of features for input video 
compare = []

vidcap = cv2.VideoCapture('/home/ketakiw/deep-learning/videos/test/3.mp4')
success,image = vidcap.read()

while success:
    success,image = vidcap.read()
    cv2.imwrite(os.path.join(os.getcwd(),'saved.jpg'), image)
    try:
        image = load_img(os.path.join(os.getcwd(),'saved.jpg'), target_size=(299, 299))
        # convert the image pixels to a numpy array
        image = img_to_array(image)
        # reshape data for the model
        image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
        # prepare the image for the VGG model
        image = keras.applications.inception_v3.preprocess_input(image)
        # get features
        feature = model.predict(image, verbose=0)
        print("features :", compare)
        # store feature
        compare.append([feature])
#         labels.append(int(label))
        print("len of features :", len(compare))
        if len(compare)==15:
            break
    except:
        pass

('features :', [])
('len of features :', 1)
('features :', [[array([[0.19502926, 0.14288607, 0.288568  , ..., 0.46150798, 1.1403977 ,
        0.05070295]], dtype=float32)]])
('len of features :', 2)
('features :', [[array([[0.19502926, 0.14288607, 0.288568  , ..., 0.46150798, 1.1403977 ,
        0.05070295]], dtype=float32)], [array([[0.16283873, 0.18465488, 0.2621465 , ..., 0.31097156, 0.71615535,
        0.21927722]], dtype=float32)]])
('len of features :', 3)
('features :', [[array([[0.19502926, 0.14288607, 0.288568  , ..., 0.46150798, 1.1403977 ,
        0.05070295]], dtype=float32)], [array([[0.16283873, 0.18465488, 0.2621465 , ..., 0.31097156, 0.71615535,
        0.21927722]], dtype=float32)], [array([[0.18127196, 0.20347397, 0.26857194, ..., 0.47507805, 1.0618632 ,
        0.13489048]], dtype=float32)]])
('len of features :', 4)
('features :', [[array([[0.19502926, 0.14288607, 0.288568  , ..., 0.46150798, 1.1403977 ,
        0.05070295]], dtype=float32)], [array([[0.16283873, 0.

('features :', [[array([[0.19502926, 0.14288607, 0.288568  , ..., 0.46150798, 1.1403977 ,
        0.05070295]], dtype=float32)], [array([[0.16283873, 0.18465488, 0.2621465 , ..., 0.31097156, 0.71615535,
        0.21927722]], dtype=float32)], [array([[0.18127196, 0.20347397, 0.26857194, ..., 0.47507805, 1.0618632 ,
        0.13489048]], dtype=float32)], [array([[0.19804619, 0.16859904, 0.1929321 , ..., 0.32173   , 0.63061994,
        0.21132004]], dtype=float32)], [array([[0.22065009, 0.19047184, 0.2103599 , ..., 0.27428827, 0.7738479 ,
        0.0320866 ]], dtype=float32)], [array([[0.31240797, 0.23245272, 0.24827789, ..., 0.30232295, 0.8244074 ,
        0.03815774]], dtype=float32)], [array([[0.24260484, 0.20547411, 0.23335496, ..., 0.3706031 , 0.5728779 ,
        0.08247557]], dtype=float32)], [array([[0.23492974, 0.2364521 , 0.18625882, ..., 0.3916892 , 0.7412277 ,
        0.08285537]], dtype=float32)], [array([[0.2221636 , 0.22970217, 0.2345845 , ..., 0.36381173, 0.7055883 ,
      

In [44]:
# Reshape in the RNN input format
com1 = np.array(compare)
print(com1.shape)
result = np.reshape(com1,(1,15,2048))
print(result.shape)

(15, 1, 1, 2048)
(1, 15, 2048)


In [46]:
# Predict classes/probabilities
print(test_model.predict_classes(result))
print(test_model.predict_proba(result))

[3]
[[0.1928938  0.21344739 0.21790157 0.37575725]]
